== “Terminator: Liberation” - A self-referential Terminator parody

=== About

____
It might seem preposterous to believe Emma Watson is the new Arnold
Schwarzenegger, just because they were both Hollywood's best paid
actors, and you would be right. Emma Watson is not the new Arnold
Schwarzenegger.

But Arnold Schwarzenegger will forever be remembered as the old EMMA
FUCKIN' WATSON!
____

( https://www.shlomifish.org/humour/bits/facts/Emma-Watson/[Emma Watson
Factoids by Shlomi Fish and friends] )

This repository contains the sources for an illustrated screenplay of a
self-referential Terminator parody which takes place in Tel Aviv in
https://en.wikipedia.org/wiki/Passover[Passover] 2020 around
http://www.olamot-con.org.il/[Olamot Con].

It features https://www.shlomifish.org/meta/nav-blocks/blocks/#harry_potter_sect[Emma Watson] as herself and her cosplayer, Hannah, as the evil
terminator, as well as
https://en.wikipedia.org/wiki/Arnold_Schwarzenegger[Arnold Schwarzenegger] as
himself and his cosplayer, Aharon, as the good terminator.

=== Links

* Homepage
+
http://www.shlomifish.org/humour/Terminator/Liberation/

=== Building the Screenplay

Go to `+./terminator--liberation/screenplay/+` and type `+make+` .

=== Ideas document / plot summary

The file `+./terminator--liberation/ideas/ideas.pod+` contains some
ideas and planning to put into the story. One can render it into XHTML
by typing `+make+` .
